import { Flex, TableProps } from 'antd';

export const columns: TableProps['columns'] = [
  {
    key: 'dateReceipt',
    align: 'center',
    width: 150,
    title: 'Дата поступления',
    dataIndex: 'dateReceipt',
    filterDropdown: null,
    fixed: 'left',
  },
  {
    key: 'eventDate',
    align: 'center',
    width: 150,
    title: 'Дата события',
    dataIndex: 'eventDate',
    fixed: 'left',
  },
  {
    key: 'npp.code',
    align: 'center',
    width: 100,
    title: 'АЭС',
    dataIndex: ['npp', 'code'],
  },
  {
    key: 'block.code',
    align: 'center',
    width: 100,
    title: 'Блок',
    dataIndex: ['block', 'code'],
  },
  {
    key: 'report',
    align: 'center',
    width: 200,
    title: 'Номер документа',
    dataIndex: 'report',
  },
  {
    key: 'description',
    align: 'start',
    width: 250,
    title: 'Описание события',
    dataIndex: 'description',
  },
  {
    key: 'typeEvent',
    align: 'center',
    width: 120,
    title: 'Тип события',
    dataIndex: 'typeEvent',
    filterDropdown: null,
  },
  {
    key: 'typeReport',
    align: 'center',
    width: 120,
    title: 'Тип отчета',
    dataIndex: 'typeReport',
    filterDropdown: null,
  },
  {
    key: 'category',
    align: 'center',
    width: 110,
    title: 'Категория',
    dataIndex: 'category',
    filterDropdown: null,
  },
  {
    key: 'inesName',
    align: 'center',
    width: 110,
    title: 'ИНЕС',
    dataIndex: 'inesName',
    filterDropdown: null,
  },
  {
    key: 'consider',
    align: 'center',
    width: 150,
    title: 'Учитывается?',
    dataIndex: 'consider',
  },
  {
    key: 'input',
    align: 'center',
    width: 120,
    title: 'Ручное?',
    dataIndex: 'input',
  },
  {
    title: 'Действия',
    dataIndex: 'id',
    key: 'lzmkabymii8e2fg1w6s',
    align: 'center',
    width: '120px',
    fixed: 'right',
    render: (_, record) => {
      return (
        <Flex gap='small'>
          <div>ffdf</div>
        </Flex>
      );
    },
  },
];

export const dataDefault = {
  content: [
    {
      id: 875,
      block: {
        id: 1,
        npp: {
          id: 54,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'БАЛ',
          name: 'Балаковская АЭС',
          description: 'Балаковская атомная электростанция',
          parentId: {
            id: 157,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'КРЭА',
            name: 'Концерн Росэнергоатом',
            description: 'АО «Концерн Росэнергоатом»',
            parentId: null,
            externalCode: 'np1',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: null,
          },
          externalCode: 'np7',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: 2,
        },
        reactorType: {
          id: 69,
          dictTypeEntity: {
            id: 4,
            code: 'reactor',
            name: 'Типы реакторов',
            description: 'Типы реакторов',
            icon: null,
            parentId: null,
            num: 14,
            isActive: true,
          },
          code: 'ВВЭР',
          name: 'Водо-водяной энергетический реактор',
          description: 'Водо-водяной энергетический реактор',
          parentId: null,
          externalCode: null,
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        reactorName: 'ВВЭР-1000',
        code: 'БАЛ-1',
        ksCop:
          '\\\\FE-KSCPAF\\Модель\\Росэнергоатом\\Балаковская АЭС\\Энергоблок 1|Выработка_мес_ни_опер_сводка',
        ny: 1000.045,
        exclude: false,
        isActive: true,
        externalCode: '4',
        oldId: 2,
      },
      report: '100000',
      description: '100000',
      typeEvent: '100000',
      category: '100000',
      consider: false,
      input: true,
      npp: {
        id: 54,
        dictTypeEntity: {
          id: 5,
          code: 'npp_code',
          name: 'Станции',
          description: 'Список всех станций',
          icon: null,
          parentId: null,
          num: 12,
          isActive: true,
        },
        code: 'БАЛ',
        name: 'Балаковская АЭС',
        description: 'Балаковская атомная электростанция',
        parentId: {
          id: 157,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'КРЭА',
          name: 'Концерн Росэнергоатом',
          description: 'АО «Концерн Росэнергоатом»',
          parentId: null,
          externalCode: 'np1',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        externalCode: 'np7',
        eventDate: null,
        endDate: null,
        isActive: true,
        oldId: 2,
      },
      typeReport: '100000',
      eventDate: '2024-04-27',
      inesName: '100000',
      dateReceipt: '2024-04-27',
      compain: {
        id: 92,
        name: '2024-1',
        isActive: false,
        oldCampain: null,
        oldName: null,
      },
      doc: null,
      a: true,
      m: null,
      la: null,
      e1: null,
      n: null,
      h: true,
      h1: null,
      t: null,
      hr: null,
      hg: true,
      hai: null,
      hwas: null,
      p: true,
      ignore: false,
      url: null,
      entityChildrenDTO: [],
      kfm: true,
      kfs: null,
    },
    {
      id: 873,
      block: {
        id: 1,
        npp: {
          id: 54,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'БАЛ',
          name: 'Балаковская АЭС',
          description: 'Балаковская атомная электростанция',
          parentId: {
            id: 157,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'КРЭА',
            name: 'Концерн Росэнергоатом',
            description: 'АО «Концерн Росэнергоатом»',
            parentId: null,
            externalCode: 'np1',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: null,
          },
          externalCode: 'np7',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: 2,
        },
        reactorType: {
          id: 69,
          dictTypeEntity: {
            id: 4,
            code: 'reactor',
            name: 'Типы реакторов',
            description: 'Типы реакторов',
            icon: null,
            parentId: null,
            num: 14,
            isActive: true,
          },
          code: 'ВВЭР',
          name: 'Водо-водяной энергетический реактор',
          description: 'Водо-водяной энергетический реактор',
          parentId: null,
          externalCode: null,
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        reactorName: 'ВВЭР-1000',
        code: 'БАЛ-1',
        ksCop:
          '\\\\FE-KSCPAF\\Модель\\Росэнергоатом\\Балаковская АЭС\\Энергоблок 1|Выработка_мес_ни_опер_сводка',
        ny: 1000.045,
        exclude: false,
        isActive: true,
        externalCode: '4',
        oldId: 2,
      },
      report: 'rep',
      description: 'rep',
      typeEvent: 'rep',
      category: 'rep',
      consider: false,
      input: true,
      npp: {
        id: 54,
        dictTypeEntity: {
          id: 5,
          code: 'npp_code',
          name: 'Станции',
          description: 'Список всех станций',
          icon: null,
          parentId: null,
          num: 12,
          isActive: true,
        },
        code: 'БАЛ',
        name: 'Балаковская АЭС',
        description: 'Балаковская атомная электростанция',
        parentId: {
          id: 157,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'КРЭА',
          name: 'Концерн Росэнергоатом',
          description: 'АО «Концерн Росэнергоатом»',
          parentId: null,
          externalCode: 'np1',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        externalCode: 'np7',
        eventDate: null,
        endDate: null,
        isActive: true,
        oldId: 2,
      },
      typeReport: 'rep',
      eventDate: '2024-04-05',
      inesName: 'rep',
      dateReceipt: '2024-04-05',
      compain: {
        id: 92,
        name: '2024-1',
        isActive: false,
        oldCampain: null,
        oldName: null,
      },
      doc: null,
      a: true,
      m: null,
      la: null,
      e1: null,
      n: null,
      h: null,
      h1: null,
      t: null,
      hr: null,
      hg: true,
      hai: null,
      hwas: null,
      p: true,
      ignore: false,
      url: null,
      entityChildrenDTO: [],
      kfm: null,
      kfs: null,
    },
    {
      id: 874,
      block: {
        id: 42,
        npp: {
          id: 53,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'ПАТЭС',
          name: 'ПАТЭС',
          description: 'Плавучая атомная теплоэлектростанция',
          parentId: {
            id: 157,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'КРЭА',
            name: 'Концерн Росэнергоатом',
            description: 'АО «Концерн Росэнергоатом»',
            parentId: null,
            externalCode: 'np1',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: null,
          },
          externalCode: 'np6',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: 12,
        },
        reactorType: {
          id: 72,
          dictTypeEntity: {
            id: 4,
            code: 'reactor',
            name: 'Типы реакторов',
            description: 'Типы реакторов',
            icon: null,
            parentId: null,
            num: 14,
            isActive: true,
          },
          code: 'КЛТ',
          name: 'Ядерная паропроизводящая установка (ЯППУ)',
          description: 'Ядерная паропроизводящая установка (ЯППУ)',
          parentId: null,
          externalCode: null,
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        reactorName: 'КЛТ-40',
        code: 'ПЭБру-1',
        ksCop:
          '\\\\FE-KSCP-AF\\Модель\\Росэнергоатом\\ПАТЭС Певек\\Энергоблок 1|Выработка_мес_ни_опер_сводка',
        ny: 40,
        exclude: false,
        isActive: true,
        externalCode: '1',
        oldId: 43,
      },
      report: 'тест ПАТЭС',
      description: 'тест ПАТЭС',
      typeEvent: 'нарушение',
      category: 'тест ПАТЭС',
      consider: true,
      input: true,
      npp: {
        id: 53,
        dictTypeEntity: {
          id: 5,
          code: 'npp_code',
          name: 'Станции',
          description: 'Список всех станций',
          icon: null,
          parentId: null,
          num: 12,
          isActive: true,
        },
        code: 'ПАТЭС',
        name: 'ПАТЭС',
        description: 'Плавучая атомная теплоэлектростанция',
        parentId: {
          id: 157,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'КРЭА',
          name: 'Концерн Росэнергоатом',
          description: 'АО «Концерн Росэнергоатом»',
          parentId: null,
          externalCode: 'np1',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        externalCode: 'np6',
        eventDate: null,
        endDate: null,
        isActive: true,
        oldId: 12,
      },
      typeReport: 'тест ПАТЭС',
      eventDate: '2024-04-05',
      inesName: 'тест ПАТЭС',
      dateReceipt: '2024-04-05',
      compain: {
        id: 92,
        name: '2024-1',
        isActive: false,
        oldCampain: null,
        oldName: null,
      },
      doc: null,
      a: true,
      m: null,
      la: null,
      e1: true,
      n: null,
      h: true,
      h1: true,
      t: null,
      hr: null,
      hg: true,
      hai: null,
      hwas: null,
      p: true,
      ignore: false,
      url: null,
      entityChildrenDTO: [],
      kfm: null,
      kfs: null,
    },
    {
      id: 872,
      block: {
        id: 2,
        npp: {
          id: 54,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'БАЛ',
          name: 'Балаковская АЭС',
          description: 'Балаковская атомная электростанция',
          parentId: {
            id: 157,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'КРЭА',
            name: 'Концерн Росэнергоатом',
            description: 'АО «Концерн Росэнергоатом»',
            parentId: null,
            externalCode: 'np1',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: null,
          },
          externalCode: 'np7',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: 2,
        },
        reactorType: {
          id: 69,
          dictTypeEntity: {
            id: 4,
            code: 'reactor',
            name: 'Типы реакторов',
            description: 'Типы реакторов',
            icon: null,
            parentId: null,
            num: 14,
            isActive: true,
          },
          code: 'ВВЭР',
          name: 'Водо-водяной энергетический реактор',
          description: 'Водо-водяной энергетический реактор',
          parentId: null,
          externalCode: null,
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        reactorName: 'ВВЭР1000',
        code: 'БАЛ-2',
        ksCop:
          '\\\\FE-KSCP-AF\\Модель\\Росэнергоатом\\Балаковская АЭС\\Энергоблок 2|Выработка_мес_ни_опер_сводка',
        ny: 1000,
        exclude: false,
        isActive: true,
        externalCode: '1',
        oldId: 3,
      },
      report: '55',
      description: '555',
      typeEvent: '55555',
      category: '55',
      consider: false,
      input: true,
      npp: {
        id: 54,
        dictTypeEntity: {
          id: 5,
          code: 'npp_code',
          name: 'Станции',
          description: 'Список всех станций',
          icon: null,
          parentId: null,
          num: 12,
          isActive: true,
        },
        code: 'БАЛ',
        name: 'Балаковская АЭС',
        description: 'Балаковская атомная электростанция',
        parentId: {
          id: 157,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'КРЭА',
          name: 'Концерн Росэнергоатом',
          description: 'АО «Концерн Росэнергоатом»',
          parentId: null,
          externalCode: 'np1',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        externalCode: 'np7',
        eventDate: null,
        endDate: null,
        isActive: true,
        oldId: 2,
      },
      typeReport: '555',
      eventDate: '2024-04-02',
      inesName: '55',
      dateReceipt: '2024-04-02',
      compain: {
        id: 87,
        name: '2023-3',
        isActive: false,
        oldCampain: '2023-09-30',
        oldName: '3-й квартал 2023 г.',
      },
      doc: null,
      a: true,
      m: null,
      la: null,
      e1: null,
      n: null,
      h: null,
      h1: null,
      t: null,
      hr: null,
      hg: true,
      hai: null,
      hwas: null,
      p: null,
      ignore: true,
      url: null,
      entityChildrenDTO: [
        {
          id: 871,
          block: {
            id: 83,
            npp: {
              id: 54,
              dictTypeEntity: {
                id: 5,
                code: 'npp_code',
                name: 'Станции',
                description: 'Список всех станций',
                icon: null,
                parentId: null,
                num: 12,
                isActive: true,
              },
              code: 'БАЛ',
              name: 'Балаковская АЭС',
              description: 'Балаковская атомная электростанция',
              parentId: {
                id: 157,
                dictTypeEntity: {
                  id: 5,
                  code: 'npp_code',
                  name: 'Станции',
                  description: 'Список всех станций',
                  icon: null,
                  parentId: null,
                  num: 12,
                  isActive: true,
                },
                code: 'КРЭА',
                name: 'Концерн Росэнергоатом',
                description: 'АО «Концерн Росэнергоатом»',
                parentId: null,
                externalCode: 'np1',
                eventDate: null,
                endDate: null,
                isActive: true,
                oldId: null,
              },
              externalCode: 'np7',
              eventDate: null,
              endDate: null,
              isActive: true,
              oldId: 2,
            },
            reactorType: {
              id: 344,
              dictTypeEntity: {
                id: 4,
                code: 'reactor',
                name: 'Типы реакторов',
                description: 'Типы реакторов',
                icon: null,
                parentId: null,
                num: 14,
                isActive: true,
              },
              code: '01',
              name: '01212',
              description: '0',
              parentId: null,
              externalCode: null,
              eventDate: null,
              endDate: null,
              isActive: true,
              oldId: null,
            },
            reactorName: '111',
            code: '1111',
            ksCop: '1',
            ny: 1,
            exclude: true,
            isActive: true,
            externalCode: null,
            oldId: null,
          },
          report: 'test1212',
          description: 'test1212',
          typeEvent: 'test121',
          category: 'test1212',
          consider: false,
          input: true,
          npp: {
            id: 54,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'БАЛ',
            name: 'Балаковская АЭС',
            description: 'Балаковская атомная электростанция',
            parentId: {
              id: 157,
              dictTypeEntity: {
                id: 5,
                code: 'npp_code',
                name: 'Станции',
                description: 'Список всех станций',
                icon: null,
                parentId: null,
                num: 12,
                isActive: true,
              },
              code: 'КРЭА',
              name: 'Концерн Росэнергоатом',
              description: 'АО «Концерн Росэнергоатом»',
              parentId: null,
              externalCode: 'np1',
              eventDate: null,
              endDate: null,
              isActive: true,
              oldId: null,
            },
            externalCode: 'np7',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: 2,
          },
          typeReport: 'test1212',
          eventDate: '2024-03-13',
          inesName: 'test1212',
          dateReceipt: '2024-03-11',
          compain: {
            id: 92,
            name: '2024-1',
            isActive: false,
            oldCampain: null,
            oldName: null,
          },
          doc: null,
          a: true,
          m: null,
          la: null,
          e1: null,
          n: null,
          h: true,
          h1: null,
          t: null,
          hr: null,
          hg: true,
          hai: null,
          hwas: null,
          p: true,
          ignore: true,
          parentId: 871,
          url: null,
          kfm: true,
          kfs: null,
        },
      ],
      kfm: null,
      kfs: null,
    },
    {
      id: 868,
      block: {
        id: 1,
        npp: {
          id: 54,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'БАЛ',
          name: 'Балаковская АЭС',
          description: 'Балаковская атомная электростанция',
          parentId: {
            id: 157,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'КРЭА',
            name: 'Концерн Росэнергоатом',
            description: 'АО «Концерн Росэнергоатом»',
            parentId: null,
            externalCode: 'np1',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: null,
          },
          externalCode: 'np7',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: 2,
        },
        reactorType: {
          id: 69,
          dictTypeEntity: {
            id: 4,
            code: 'reactor',
            name: 'Типы реакторов',
            description: 'Типы реакторов',
            icon: null,
            parentId: null,
            num: 14,
            isActive: true,
          },
          code: 'ВВЭР',
          name: 'Водо-водяной энергетический реактор',
          description: 'Водо-водяной энергетический реактор',
          parentId: null,
          externalCode: null,
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        reactorName: 'ВВЭР-1000',
        code: 'БАЛ-1',
        ksCop:
          '\\\\FE-KSCPAF\\Модель\\Росэнергоатом\\Балаковская АЭС\\Энергоблок 1|Выработка_мес_ни_опер_сводка',
        ny: 1000.045,
        exclude: false,
        isActive: true,
        externalCode: '4',
        oldId: 2,
      },
      report: null,
      description: '1',
      typeEvent: '1',
      category: null,
      consider: false,
      input: true,
      npp: {
        id: 54,
        dictTypeEntity: {
          id: 5,
          code: 'npp_code',
          name: 'Станции',
          description: 'Список всех станций',
          icon: null,
          parentId: null,
          num: 12,
          isActive: true,
        },
        code: 'БАЛ',
        name: 'Балаковская АЭС',
        description: 'Балаковская атомная электростанция',
        parentId: {
          id: 157,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'КРЭА',
          name: 'Концерн Росэнергоатом',
          description: 'АО «Концерн Росэнергоатом»',
          parentId: null,
          externalCode: 'np1',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        externalCode: 'np7',
        eventDate: null,
        endDate: null,
        isActive: true,
        oldId: 2,
      },
      typeReport: null,
      eventDate: '2024-03-11',
      inesName: null,
      dateReceipt: '2024-03-11',
      compain: {
        id: 92,
        name: '2024-1',
        isActive: false,
        oldCampain: null,
        oldName: null,
      },
      doc: null,
      a: true,
      m: null,
      la: null,
      e1: null,
      n: null,
      h: null,
      h1: null,
      t: null,
      hr: null,
      hg: true,
      hai: null,
      hwas: null,
      p: null,
      ignore: true,
      url: null,
      entityChildrenDTO: [],
      kfm: null,
      kfs: null,
    },
    {
      id: 870,
      block: {
        id: 83,
        npp: {
          id: 54,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'БАЛ',
          name: 'Балаковская АЭС',
          description: 'Балаковская атомная электростанция',
          parentId: {
            id: 157,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'КРЭА',
            name: 'Концерн Росэнергоатом',
            description: 'АО «Концерн Росэнергоатом»',
            parentId: null,
            externalCode: 'np1',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: null,
          },
          externalCode: 'np7',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: 2,
        },
        reactorType: {
          id: 344,
          dictTypeEntity: {
            id: 4,
            code: 'reactor',
            name: 'Типы реакторов',
            description: 'Типы реакторов',
            icon: null,
            parentId: null,
            num: 14,
            isActive: true,
          },
          code: '01',
          name: '01212',
          description: '0',
          parentId: null,
          externalCode: null,
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        reactorName: '111',
        code: '1111',
        ksCop: '1',
        ny: 1,
        exclude: true,
        isActive: true,
        externalCode: null,
        oldId: null,
      },
      report: null,
      description: 'test',
      typeEvent: 'test',
      category: null,
      consider: false,
      input: true,
      npp: {
        id: 54,
        dictTypeEntity: {
          id: 5,
          code: 'npp_code',
          name: 'Станции',
          description: 'Список всех станций',
          icon: null,
          parentId: null,
          num: 12,
          isActive: true,
        },
        code: 'БАЛ',
        name: 'Балаковская АЭС',
        description: 'Балаковская атомная электростанция',
        parentId: {
          id: 157,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'КРЭА',
          name: 'Концерн Росэнергоатом',
          description: 'АО «Концерн Росэнергоатом»',
          parentId: null,
          externalCode: 'np1',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        externalCode: 'np7',
        eventDate: null,
        endDate: null,
        isActive: true,
        oldId: 2,
      },
      typeReport: null,
      eventDate: '2024-03-10',
      inesName: null,
      dateReceipt: '2024-03-11',
      compain: {
        id: 92,
        name: '2024-1',
        isActive: false,
        oldCampain: null,
        oldName: null,
      },
      doc: null,
      a: true,
      m: true,
      la: null,
      e1: true,
      n: null,
      h: true,
      h1: null,
      t: null,
      hr: null,
      hg: true,
      hai: null,
      hwas: null,
      p: true,
      ignore: true,
      url: null,
      entityChildrenDTO: [],
      kfm: true,
      kfs: null,
    },
    {
      id: 814,
      block: {
        id: 2,
        npp: {
          id: 54,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'БАЛ',
          name: 'Балаковская АЭС',
          description: 'Балаковская атомная электростанция',
          parentId: {
            id: 157,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'КРЭА',
            name: 'Концерн Росэнергоатом',
            description: 'АО «Концерн Росэнергоатом»',
            parentId: null,
            externalCode: 'np1',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: null,
          },
          externalCode: 'np7',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: 2,
        },
        reactorType: {
          id: 69,
          dictTypeEntity: {
            id: 4,
            code: 'reactor',
            name: 'Типы реакторов',
            description: 'Типы реакторов',
            icon: null,
            parentId: null,
            num: 14,
            isActive: true,
          },
          code: 'ВВЭР',
          name: 'Водо-водяной энергетический реактор',
          description: 'Водо-водяной энергетический реактор',
          parentId: null,
          externalCode: null,
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        reactorName: 'ВВЭР1000',
        code: 'БАЛ-2',
        ksCop:
          '\\\\FE-KSCP-AF\\Модель\\Росэнергоатом\\Балаковская АЭС\\Энергоблок 2|Выработка_мес_ни_опер_сводка',
        ny: 1000,
        exclude: false,
        isActive: true,
        externalCode: '1',
        oldId: 3,
      },
      report: null,
      description: 'тест',
      typeEvent: 'тест',
      category: null,
      consider: false,
      input: true,
      npp: {
        id: 54,
        dictTypeEntity: {
          id: 5,
          code: 'npp_code',
          name: 'Станции',
          description: 'Список всех станций',
          icon: null,
          parentId: null,
          num: 12,
          isActive: true,
        },
        code: 'БАЛ',
        name: 'Балаковская АЭС',
        description: 'Балаковская атомная электростанция',
        parentId: {
          id: 157,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'КРЭА',
          name: 'Концерн Росэнергоатом',
          description: 'АО «Концерн Росэнергоатом»',
          parentId: null,
          externalCode: 'np1',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        externalCode: 'np7',
        eventDate: null,
        endDate: null,
        isActive: true,
        oldId: 2,
      },
      typeReport: null,
      eventDate: '2024-03-07',
      inesName: null,
      dateReceipt: '2024-03-05',
      compain: {
        id: 92,
        name: '2024-1',
        isActive: false,
        oldCampain: null,
        oldName: null,
      },
      doc: null,
      a: true,
      m: null,
      la: null,
      e1: null,
      n: null,
      h: true,
      h1: null,
      t: null,
      hr: null,
      hg: null,
      hai: null,
      hwas: null,
      p: true,
      ignore: true,
      url: null,
      entityChildrenDTO: [
        {
          id: 812,
          block: {
            id: 1,
            npp: {
              id: 54,
              dictTypeEntity: {
                id: 5,
                code: 'npp_code',
                name: 'Станции',
                description: 'Список всех станций',
                icon: null,
                parentId: null,
                num: 12,
                isActive: true,
              },
              code: 'БАЛ',
              name: 'Балаковская АЭС',
              description: 'Балаковская атомная электростанция',
              parentId: {
                id: 157,
                dictTypeEntity: {
                  id: 5,
                  code: 'npp_code',
                  name: 'Станции',
                  description: 'Список всех станций',
                  icon: null,
                  parentId: null,
                  num: 12,
                  isActive: true,
                },
                code: 'КРЭА',
                name: 'Концерн Росэнергоатом',
                description: 'АО «Концерн Росэнергоатом»',
                parentId: null,
                externalCode: 'np1',
                eventDate: null,
                endDate: null,
                isActive: true,
                oldId: null,
              },
              externalCode: 'np7',
              eventDate: null,
              endDate: null,
              isActive: true,
              oldId: 2,
            },
            reactorType: {
              id: 69,
              dictTypeEntity: {
                id: 4,
                code: 'reactor',
                name: 'Типы реакторов',
                description: 'Типы реакторов',
                icon: null,
                parentId: null,
                num: 14,
                isActive: true,
              },
              code: 'ВВЭР',
              name: 'Водо-водяной энергетический реактор',
              description: 'Водо-водяной энергетический реактор',
              parentId: null,
              externalCode: null,
              eventDate: null,
              endDate: null,
              isActive: true,
              oldId: null,
            },
            reactorName: 'ВВЭР-1000',
            code: 'БАЛ-1',
            ksCop:
              '\\\\FE-KSCPAF\\Модель\\Росэнергоатом\\Балаковская АЭС\\Энергоблок 1|Выработка_мес_ни_опер_сводка',
            ny: 1000.045,
            exclude: false,
            isActive: true,
            externalCode: '4',
            oldId: 2,
          },
          report: null,
          description: 'тест',
          typeEvent: 'тест',
          category: null,
          consider: false,
          input: true,
          npp: {
            id: 54,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'БАЛ',
            name: 'Балаковская АЭС',
            description: 'Балаковская атомная электростанция',
            parentId: {
              id: 157,
              dictTypeEntity: {
                id: 5,
                code: 'npp_code',
                name: 'Станции',
                description: 'Список всех станций',
                icon: null,
                parentId: null,
                num: 12,
                isActive: true,
              },
              code: 'КРЭА',
              name: 'Концерн Росэнергоатом',
              description: 'АО «Концерн Росэнергоатом»',
              parentId: null,
              externalCode: 'np1',
              eventDate: null,
              endDate: null,
              isActive: true,
              oldId: null,
            },
            externalCode: 'np7',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: 2,
          },
          typeReport: null,
          eventDate: '2024-03-05',
          inesName: null,
          dateReceipt: '2024-03-05',
          compain: {
            id: 92,
            name: '2024-1',
            isActive: false,
            oldCampain: null,
            oldName: null,
          },
          doc: null,
          a: null,
          m: null,
          la: null,
          e1: null,
          n: null,
          h: null,
          h1: null,
          t: null,
          hr: null,
          hg: null,
          hai: null,
          hwas: null,
          p: null,
          ignore: true,
          parentId: 812,
          url: null,
          kfm: null,
          kfs: null,
        },
      ],
      kfm: null,
      kfs: null,
    },
    {
      id: 815,
      block: {
        id: 1,
        npp: {
          id: 54,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'БАЛ',
          name: 'Балаковская АЭС',
          description: 'Балаковская атомная электростанция',
          parentId: {
            id: 157,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'КРЭА',
            name: 'Концерн Росэнергоатом',
            description: 'АО «Концерн Росэнергоатом»',
            parentId: null,
            externalCode: 'np1',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: null,
          },
          externalCode: 'np7',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: 2,
        },
        reactorType: {
          id: 69,
          dictTypeEntity: {
            id: 4,
            code: 'reactor',
            name: 'Типы реакторов',
            description: 'Типы реакторов',
            icon: null,
            parentId: null,
            num: 14,
            isActive: true,
          },
          code: 'ВВЭР',
          name: 'Водо-водяной энергетический реактор',
          description: 'Водо-водяной энергетический реактор',
          parentId: null,
          externalCode: null,
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        reactorName: 'ВВЭР-1000',
        code: 'БАЛ-1',
        ksCop:
          '\\\\FE-KSCPAF\\Модель\\Росэнергоатом\\Балаковская АЭС\\Энергоблок 1|Выработка_мес_ни_опер_сводка',
        ny: 1000.045,
        exclude: false,
        isActive: true,
        externalCode: '4',
        oldId: 2,
      },
      report: null,
      description: 'тест',
      typeEvent: 'тест',
      category: null,
      consider: false,
      input: true,
      npp: {
        id: 54,
        dictTypeEntity: {
          id: 5,
          code: 'npp_code',
          name: 'Станции',
          description: 'Список всех станций',
          icon: null,
          parentId: null,
          num: 12,
          isActive: true,
        },
        code: 'БАЛ',
        name: 'Балаковская АЭС',
        description: 'Балаковская атомная электростанция',
        parentId: {
          id: 157,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'КРЭА',
          name: 'Концерн Росэнергоатом',
          description: 'АО «Концерн Росэнергоатом»',
          parentId: null,
          externalCode: 'np1',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        externalCode: 'np7',
        eventDate: null,
        endDate: null,
        isActive: true,
        oldId: 2,
      },
      typeReport: null,
      eventDate: '2024-03-05',
      inesName: null,
      dateReceipt: '2024-03-05',
      compain: {
        id: 92,
        name: '2024-1',
        isActive: false,
        oldCampain: null,
        oldName: null,
      },
      doc: null,
      a: true,
      m: true,
      la: null,
      e1: true,
      n: null,
      h: true,
      h1: true,
      t: null,
      hr: null,
      hg: true,
      hai: null,
      hwas: null,
      p: true,
      ignore: false,
      url: null,
      entityChildrenDTO: [],
      kfm: null,
      kfs: true,
    },
    {
      id: 813,
      block: {
        id: 1,
        npp: {
          id: 54,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'БАЛ',
          name: 'Балаковская АЭС',
          description: 'Балаковская атомная электростанция',
          parentId: {
            id: 157,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'КРЭА',
            name: 'Концерн Росэнергоатом',
            description: 'АО «Концерн Росэнергоатом»',
            parentId: null,
            externalCode: 'np1',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: null,
          },
          externalCode: 'np7',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: 2,
        },
        reactorType: {
          id: 69,
          dictTypeEntity: {
            id: 4,
            code: 'reactor',
            name: 'Типы реакторов',
            description: 'Типы реакторов',
            icon: null,
            parentId: null,
            num: 14,
            isActive: true,
          },
          code: 'ВВЭР',
          name: 'Водо-водяной энергетический реактор',
          description: 'Водо-водяной энергетический реактор',
          parentId: null,
          externalCode: null,
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        reactorName: 'ВВЭР-1000',
        code: 'БАЛ-1',
        ksCop:
          '\\\\FE-KSCPAF\\Модель\\Росэнергоатом\\Балаковская АЭС\\Энергоблок 1|Выработка_мес_ни_опер_сводка',
        ny: 1000.045,
        exclude: false,
        isActive: true,
        externalCode: '4',
        oldId: 2,
      },
      report: null,
      description: 'тест',
      typeEvent: 'тест',
      category: null,
      consider: false,
      input: true,
      npp: {
        id: 54,
        dictTypeEntity: {
          id: 5,
          code: 'npp_code',
          name: 'Станции',
          description: 'Список всех станций',
          icon: null,
          parentId: null,
          num: 12,
          isActive: true,
        },
        code: 'БАЛ',
        name: 'Балаковская АЭС',
        description: 'Балаковская атомная электростанция',
        parentId: {
          id: 157,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'КРЭА',
          name: 'Концерн Росэнергоатом',
          description: 'АО «Концерн Росэнергоатом»',
          parentId: null,
          externalCode: 'np1',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        externalCode: 'np7',
        eventDate: null,
        endDate: null,
        isActive: true,
        oldId: 2,
      },
      typeReport: null,
      eventDate: '2024-03-05',
      inesName: null,
      dateReceipt: '2024-03-05',
      compain: {
        id: 92,
        name: '2024-1',
        isActive: false,
        oldCampain: null,
        oldName: null,
      },
      doc: null,
      a: true,
      m: null,
      la: null,
      e1: null,
      n: null,
      h: null,
      h1: null,
      t: null,
      hr: null,
      hg: true,
      hai: null,
      hwas: null,
      p: null,
      ignore: false,
      url: null,
      entityChildrenDTO: [],
      kfm: true,
      kfs: null,
    },
    {
      id: 809,
      block: {
        id: 31,
        npp: {
          id: 50,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'НВО',
          name: 'Нововоронежская АЭС',
          description: 'Нововоронежская атомная электростанция',
          parentId: {
            id: 157,
            dictTypeEntity: {
              id: 5,
              code: 'npp_code',
              name: 'Станции',
              description: 'Список всех станций',
              icon: null,
              parentId: null,
              num: 12,
              isActive: true,
            },
            code: 'КРЭА',
            name: 'Концерн Росэнергоатом',
            description: 'АО «Концерн Росэнергоатом»',
            parentId: null,
            externalCode: 'np1',
            eventDate: null,
            endDate: null,
            isActive: true,
            oldId: null,
          },
          externalCode: 'np3',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: 9,
        },
        reactorType: {
          id: 69,
          dictTypeEntity: {
            id: 4,
            code: 'reactor',
            name: 'Типы реакторов',
            description: 'Типы реакторов',
            icon: null,
            parentId: null,
            num: 14,
            isActive: true,
          },
          code: 'ВВЭР',
          name: 'Водо-водяной энергетический реактор',
          description: 'Водо-водяной энергетический реактор',
          parentId: null,
          externalCode: null,
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        reactorName: 'ВВЭР440',
        code: 'НВО-4',
        ksCop:
          '\\\\FE-KSCP-AF\\Модель\\Росэнергоатом\\Нововоронежская АЭС\\Энергоблок 4|Выработка_мес_ни_опер_сводка',
        ny: 440,
        exclude: false,
        isActive: true,
        externalCode: '1',
        oldId: 32,
      },
      report: 'В стадии расследования',
      description: 'В стадии расследования',
      typeEvent: 'Отклонение',
      category: 'П02',
      consider: false,
      input: true,
      npp: {
        id: 50,
        dictTypeEntity: {
          id: 5,
          code: 'npp_code',
          name: 'Станции',
          description: 'Список всех станций',
          icon: null,
          parentId: null,
          num: 12,
          isActive: true,
        },
        code: 'НВО',
        name: 'Нововоронежская АЭС',
        description: 'Нововоронежская атомная электростанция',
        parentId: {
          id: 157,
          dictTypeEntity: {
            id: 5,
            code: 'npp_code',
            name: 'Станции',
            description: 'Список всех станций',
            icon: null,
            parentId: null,
            num: 12,
            isActive: true,
          },
          code: 'КРЭА',
          name: 'Концерн Росэнергоатом',
          description: 'АО «Концерн Росэнергоатом»',
          parentId: null,
          externalCode: 'np1',
          eventDate: null,
          endDate: null,
          isActive: true,
          oldId: null,
        },
        externalCode: 'np3',
        eventDate: null,
        endDate: null,
        isActive: true,
        oldId: 9,
      },
      typeReport: '',
      eventDate: '2023-12-29',
      inesName: 'Вне шкалы',
      dateReceipt: '2023-12-30',
      compain: {
        id: 88,
        name: '2023-4',
        isActive: false,
        oldCampain: '2023-12-31',
        oldName: '4-й квартал 2023 г.',
      },
      doc: null,
      a: true,
      m: false,
      la: false,
      e1: false,
      n: false,
      h: false,
      h1: false,
      t: false,
      hr: false,
      hg: false,
      hai: false,
      hwas: false,
      p: false,
      ignore: false,
      url: null,
      entityChildrenDTO: [],
      kfm: false,
      kfs: false,
    },
  ],
  totalElements: 108,
  totalPages: 11,
};
